project:
  type: website
  output-dir: docs

website:
  title: "Data Worker"
  navbar:
    left:
      - text: "Portfolio"
        href: portfolio.qmd
      - text: "Experience"
        href: experience.qmd
      - text: "DataViz"
        href: dataviz.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme: cosmo
    toc: false